// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2gNOnx-SDF2TyzADiXxfmge95Lza4Fk0',
    appId: '1:1082982312894:web:afb20a233403d1066867ef',
    messagingSenderId: '1082982312894',
    projectId: 'event-shadow',
    authDomain: 'event-shadow.firebaseapp.com',
    storageBucket: 'event-shadow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBliGX9JLuQdkU47NoA3n-CtaXjWKMfhVE',
    appId: '1:1082982312894:android:d84ac997b5f8fcd06867ef',
    messagingSenderId: '1082982312894',
    projectId: 'event-shadow',
    storageBucket: 'event-shadow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDks7DWExNrCXYfNjPEOvr58AajceUohZI',
    appId: '1:1082982312894:ios:950590f2aade57b26867ef',
    messagingSenderId: '1082982312894',
    projectId: 'event-shadow',
    storageBucket: 'event-shadow.appspot.com',
    iosClientId: '1082982312894-eeujtu58phop38kr6ftgsng39uqat5gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.evntShadow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDks7DWExNrCXYfNjPEOvr58AajceUohZI',
    appId: '1:1082982312894:ios:8e0dd448178127c26867ef',
    messagingSenderId: '1082982312894',
    projectId: 'event-shadow',
    storageBucket: 'event-shadow.appspot.com',
    iosClientId: '1082982312894-qen6bu5sf2lq3u1dgn4l88nh2nc1d32g.apps.googleusercontent.com',
    iosBundleId: 'com.example.evntShadow.RunnerTests',
  );
}
